apiVersion: v1
kind: Secret
metadata:
  name: github
  namespace: default
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/morten-olsen/home-server
  username: morten-olsen
  password: {{ .Values.github.pat }}
