apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-pihole"
  labels:
    app: "{{ .Release.Name }}-pihole"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-pihole"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-pihole"
    spec:
      containers:
        - name: "{{ .Release.Name }}-pihole"
          image: docker.io/pihole/pihole:2021.11
          envFrom:
            - configMapRef:
                name: "{{ .Release.Name }}-pihole-config"
            - secretRef:
                name: "{{ .Release.Name }}-pihole-secret"
          ports:
            - name: svc-53-udp
              containerPort: 53
              protocol: UDP
            - name: svc-53-tcp
              containerPort: 53
              protocol: TCP
            - name: svc-ui
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              port: svc-ui
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              port: svc-ui
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 10
          resources:
            limits:
              memory: "300Mi"
              cpu: "250m"
            requests:
              memory: "50Mi"
              cpu: "100m"
          volumeMounts:
            - mountPath: /etc/pihole
              name: pihole-etc
      volumes:
        - name: pihole-etc
          persistentVolumeClaim:
            claimName: pvc-{{ .Release.Name }}-pihole-data
