apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-pihole-dns-udp"
spec:
  selector:
    app: "{{ .Release.Name }}-pihole"
  ports:
    - name: 53-udp
      port: 53
      targetPort: 53
      protocol: UDP
  externalTrafficPolicy: Local
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 192.168.20.1241
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-pihole-dns-tcp"
spec:
  selector:
    app: pihole
    app: "{{ .Release.Name }}-pihole"
  namespace: pihole
  ports:
    - name: 53-tcp
      port: 53
      targetPort: 53
      protocol: TCP
  externalTrafficPolicy: Local
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 192.168.20.1241
