apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-pihole-dns-udp"
spec:
  selector:
    app: "{{ .Release.Name }}-pihole"
  ports:
    - name: 53-udp
      port: 53
      targetPort: 53
      nodePort: 32053
      protocol: UDP
    - name: 53-tcp
      port: 53
      targetPort: 53
      nodePort: 32053
      protocol: TCP
  type: NodePort
