apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-{{ .Release.Name }}-notify-data
  labels:
    storage.k8s.io/name: nfs
    storage.k8s.io/part-of: kubernetes-complete-reference
    storage.k8s.io/created-by: ssbostan
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-notify-config"
data:
  server.yml: |
    # Template: https://github.com/binwiederhier/ntfy/blob/main/server/server.yml
    base-url: https://{{ .Values.subdomain }}.{{ .Values.domain }}
    # attachment-cache-dir: "/var/ntfy-data/cache/attachments"
    cache-file: "/var/ntfy-data/cache/cache.db"
    #auth-file: "/var/nfty-data/users.db"
    #auth-default-access: deny-all

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-notify-deployment"
spec:
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-notify-pod"
  replicas: 1
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-notify-pod"
    spec:
      containers:
        - image: binwiederhier/ntfy
          imagePullPolicy: Always
          name: "{{ .Release.Name }}-notify"
          args: ["serve"]
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /var/nftfy-data/
              name: data 
            - name: config
              mountPath: "/etc/ntfy"
              readOnly: true
      volumes:
        - name: data 
          persistentVolumeClaim:
            claimName: "pvc-{{ .Release.Name }}-notify-data"
        - name: config
          configMap:
            name: "{{ .Release.Name }}-notify-config"

---

apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-notify-svc"
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: "{{ .Release.Name }}-notify-pod"

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Release.Name }}-notify-ingress"
  annotations:
    cert-manager.io/issuer: "{{ .Values.issuer }}"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "*.{{ .Values.domain }}"
        - "{{ .Values.domain }}"
      secretName: "tls-secret"
  rules:
    - host: "{{ .Values.subdomain }}.{{ .Values.domain }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "{{ .Release.Name }}-notify-svc"
                port:
                  number: 80
