apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "apps-root"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    path: apps/
    repoURL: "{{ .Values.repo }}"
    helm:
      values: |
        repo: "{{ .Values.repo }}"
        revision: "{{ .Values.revision }}"
        issuer: "{{ .Values.repo }}"
    targetRevision: "{{ .Values.revision }}"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
