apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-root
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    path: infra/
    repoURL: "{{ .Values.repo }}"
    helm:
      values: |
        repo: "{{ .Values.repo }}"
        revision: "{{ .Values.revision }}"
        email: "{{ .Values.email }}"
        domain: "{{ .Values.domain }}"
        issuer: "{{ .Values.issuer }}"
    targetRevision: "{{ .Values.revision }}"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
