apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-{{ .Release.Name }}-duplicati-data
  labels:
    storage.k8s.io/name: nfs
    storage.k8s.io/part-of: kubernetes-complete-reference
    storage.k8s.io/created-by: ssbostan
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-duplicati-deployment"
spec:
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-duplicati-pod"
  replicas: 1
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-duplicati-pod"
    spec:
      containers:
        - image: duplicati/duplicati:latest
          imagePullPolicy: Always
          name: "{{ .Release.Name }}-duplicati"
          ports:
            - containerPort: 8200
          volumeMounts:
            - mountPath: /var/www/duplicati/config
              name: data 
            - mountPath: /data/apps
              name: apps
      volumes:
        - name: data 
          persistentVolumeClaim:
            claimName: "pvc-{{ .Release.Name }}-duplicati-data"
        - name: apps
          persistentVolumeClaim:
            claimName: pvc-apps

---

apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-duplicati-svc"
spec:
  ports:
    - port: 80
      targetPort: 8200
      protocol: TCP
  selector:
    app: "{{ .Release.Name }}-duplicati-pod"

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Release.Name }}-duplicati-ingress"
  annotations:
    cert-manager.io/issuer: "{{ .Values.issuer }}"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "*.{{ .Values.domain }}"
        - "{{ .Values.domain }}"
      secretName: "tls-secret"
  rules:
    - host: "{{ .Values.subdomain }}.{{ .Values.domain }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "{{ .Release.Name }}-duplicati-svc"
                port:
                  number: 80
