apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "app-media"
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    path: charts/apps/media
    repoURL: "{{ .Values.repo }}"
    targetRevision: "{{ .Values.revision }}"
    helm:
      values: |
        storage:
          host: {{ .Values.storage.host }}
        jellyfin:
          hostname: jellyfin.{{ .Values.domain }}
        issuer: {{ .Values.issuer }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
