apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: media 
  namespace: default
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-example
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: media 
  source:
    path: charts/apps/media
    repoURL: "{{ .Values.repo }}"
    targetRevision: "{{ .Values.revision }}"
    helm:
      values: |
        jellyfin:
          hostname: jellyfin.{{ .Values.domain }}
        issuer: {{ .Values.issuer }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
