apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "root"
  namespace: {{ .Values.namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.namespace }}
  project: default
  source:
    path: apps/
    repoURL: "{{ .Values.repo }}"
    targetRevision: "{{ .Values.revision }}"
    helm:
      values: {{ .Values | toJson | quote }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
