apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-demo
  labels:
    storage: demo
spec:
  storageClassName: nfs
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  #storageClassName: slow
  nfs:
    path: /mnt/HDD/Apps/demo
    server: "{{ .Values.host }}"


---


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-demo
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      storage: "demo"
