apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-pictures
  labels:
    storage: pictures
spec:
  storageClassName: nfs
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  #storageClassName: slow
  mountOptions:
    - hard
  nfs:
    path: /mnt/HDD/Pictures
    server: "{{ .Values.host }}"


---


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-pictures
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      storage: "pictures"
