apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-deployment"
spec:
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-pod"
  replicas: 1
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-pod"
    spec:
      containers:
        - image: gcr.io/kuar-demo/kuard-amd64:1
          imagePullPolicy: Always
          name: kuard
          ports:
            - containerPort: 8080
