apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: le-crt
spec:
  secretName: tls-secret
  issuerRef:
    kind: Issuer
    name: "{{ .Values.issuer }}"
  commonName: "*.{{ .Values.domain }}"
  dnsNames:
    - "{{ .Values.domain }}"
    - "*.{{ .Values.domain }}"
  acme:
    config:
      - dns01:
          provider: cloudflare
        domains:
          - example.com
          - '*.example.com'
